var wordList = [
    { word: "apple", hint: "A fruit" },
    { word: "house", hint: "A place where people live" },
    { word: "beach", hint: "Sandy shore by the sea" },
    { word: "piano", hint: "A musical instrument with keys" },
    { word: "river", hint: "A natural flowing watercourse" },
    { word: "jungle", hint: "A dense forest" },
    { word: "mount", hint: "A high natural elevation" },
    { word: "cloud", hint: "A visible mass of condensed water vapor" },
    { word: "lemon", hint: "A citrus fruit" },
    { word: "cat", hint: "A common household pet" },
    { word: "bird", hint: "A feathered animal that flies" },
    { word: "snake", hint: "A long, legless reptile" },
    { word: "music", hint: "Art form that involves sound and rhythm" },
    { word: "guitar", hint: "A musical instrument with strings" },
    { word: "sunset", hint: "The daily disappearance of the sun below the horizon" },
    { word: "coffee", hint: "A popular caffeinated beverage" },
    { word: "robot", hint: "A machine capable of carrying out complex actions" },
    { word: "ocean", hint: "A vast body of saltwater" },
    { word: "island", hint: "A landmass surrounded by water" },
    { word: "tiger", hint: "A large carnivorous feline" },
    { word: "planet", hint: "A celestial body that orbits around a star" },
    { word: "castle", hint: "A fortified building, typically with a moat" },
    { word: "rabbit", hint: "A small mammal with long ears and a fluffy tail" },
    { word: "storm", hint: "A violent atmospheric disturbance" },
    { word: "light", hint: "Electromagnetic radiation that enables sight" },
    { word: "dream", hint: "A series of thoughts, images, and sensations during sleep" },
    { word: "sword", hint: "A weapon with a long metal blade" },
    { word: "night", hint: "The period of darkness between sunset and sunrise" },
    { word: "fire", hint: "The rapid oxidation of a material with the release of heat" },
    { word: "star", hint: "A luminous celestial object" },
    { word: "smile", hint: "An expression of happiness or amusement" },
    { word: "fruit", hint: "A sweet or savory edible product of a plant" },
    { word: "money", hint: "A medium of exchange for goods and services" },
    { word: "happy", hint: "Feeling or showing pleasure or contentment" },
    { word: "green", hint: "A color often associated with nature and freshness" },
    { word: "sunny", hint: "Characterized by a bright, clear sky and abundant sunlight" },
    { word: "beauty", hint: "A combination of qualities that pleases the senses" },
    { word: "magic", hint: "The power of apparently influencing events by supernatural means" },
    { word: "peace", hint: "A state of tranquility and freedom from conflict" },
    { word: "space", hint: "The vast, seemingly infinite expanse beyond Earth" },
  
    // Add more words and hints here
  ];
  
  
