var wordList = [
    { word: "apple", hint: "A fruit" },
    { word: "banana", hint: "A tropical fruit" },
    { word: "carrot", hint: "A vegetable" },
    { word: "dog", hint: "A common pet" },
    { word: "elephant", hint: "A large animal" },
    { word: "flower", hint: "A plant with colorful petals" },
    { word: "guitar", hint: "A musical instrument" },
    { word: "house", hint: "A place where people live" },
    { word: "island", hint: "A land surrounded by water" },
    { word: "jungle", hint: "A dense forest" },
    { word: "kangaroo", hint: "A marsupial from Australia" },
    { word: "lemon", hint: "A citrus fruit" },
    { word: "mountain", hint: "A large natural elevation" },
    { word: "ninja", hint: "A skilled martial artist" },
    { word: "ocean", hint: "A vast body of saltwater" },
    { word: "piano", hint: "A musical instrument with keys" },
    { word: "queen", hint: "A female monarch" },
    { word: "rocket", hint: "A spacecraft propelled into space" },
    { word: "sailboat", hint: "A boat with sails" },
    { word: "tiger", hint: "A large carnivorous feline" },
    { word: "umbrella", hint: "A device used for protection from rain" },
    { word: "violin", hint: "A string instrument played with a bow" },
    { word: "waterfall", hint: "A cascade of water" },
    { word: "xylophone", hint: "A musical instrument with wooden bars" },
    { word: "yacht", hint: "A luxurious sailing vessel" },
    { word: "zebra", hint: "A black and white striped animal" },
    // Add more words and hints here
  ];
  